// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsável pela carteira do cliente */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Posição de prioridade do cliente na fila daquele vendedor específico */
          ordem: number;
          /** Identificador único do cliente no cadastro */
          cliente_id: number;
          /** Razão social da empresa cliente */
          razao_social: string;
          /** Cidade sede do cliente */
          cidade: string;
          /** Estado federativo do cliente */
          uf: string;
          /** Ticket médio histórico em reais dos pedidos do cliente */
          ticket_medio: number;
          /** Nome do vendedor responsável pela carteira do cliente */
          vendedor: string;
          /** Probabilidade prevista pelo modelo de o cliente realizar pedido em 7 dias */
          score: number;
          /** Segmento de temperatura da propensão calculada via NTILE(4) */
          faixa: string;
          /** Justificativa comercial em português explicando por que ligar agora */
          motivo: string;
          /** Produto recomendado para oferta com base no histórico e saldo em estoque */
          sugestao: string;
          /** Desfecho da ligação: vendeu, vai_pensar, sem_interesse ou nao_atendeu */
          retorno_status: string;
          /** Observações livres registradas pelo vendedor sobre a conversa */
          retorno_comentario: string;
          /** Data e hora exatas do registro do retorno no sistema */
          retorno_data: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType DATE */
          referencia: string;
          /** @sqlType INT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType DOUBLE */
          taxa_base: number;
          /** @sqlType BIGINT */
          ja_trabalhados: number;
          /** @sqlType BIGINT */
          viraram_pedido: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsável pela carteira do cliente */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
        }>;
      };
  }
}
